### ISSUE TITLE
Tasks to release `0.1.0`

### ISSUE THREAD

**Issue by kachick** [kachick/ruby-ulid#88]
* [x] Resolves #7 ref: #85, #93, #96
* [x] Drop deprecated old major method `ULID.monotonic_generate` ref: #94
* [x] ~Hide or drop `MonotonicGenerator` attr_accessor~ => This is needed for testability, I'll keep for now.
* [x] At least, drop deprecated methods for part of #84 ref: 0f256006b93199e99a6a6afee8a25f8d208afb00
* [x] Not crucial, but I'd like to get answer around #8, ~at least, `entropy` attr_reader should be removed~ => This is needed for testability, I'll keep for now.
* [x] Make official or remove some undocumented methods. e.g `ULID#timestamp`, `ULID#randomness` =>  https://github.com/kachick/ruby-ulid/commit/fe2cb12a33bdff553f7fe9780511242e5e12ebe5
* [x] Resolves #13 if it is possible ref: #113
* [x] Make some constants be private constants if they have not clear name #121
* [x] Make `ULID.new` as a private method for optimizations in feature. `ULID#initialize` interface might be changed and be complex ref: #107, #108

**Comment by kachick** [comment]
https://guides.rubygems.org/patterns/#semantic-versioning 👀
